version: 0.2
env:
  secrets-manager:
    DB_USER: "endgame-secret:db_user"
    DB_PASS: "endgame-secret:db_pass"
    DB_HOST: "endgame-secret:db_host"
    DB: "endgame-secret:db"
    BACKEND_URL: "endgame-secret:backend_url"
    FRONTEND_REPO_URI: "endgame-secret:fronted_repo_uri"
    REGION: "endgame-secret:region"
    ACC_NO: "endgame-secret:acc_no"
    BACKEND_REPO_URI: "endgame-secret:backend_repo_uri"
    # add the base64 encoded value of kubeconfig file in secret manager
    # use the command "base64 -w 0" to avoid the line breaks 
    SECRET_NAME: "endgame-secret:secret_name"
    ASSUME_ROLE_ARN: "endgame-secret:assume_role_arn"
    CLUSTER_NAME: "endgame-secret:cluster_name"
    GIT_USER: "endgame-secret:git_user"
    GIT_PAT: "endgame-secret:git_pat"
    GIT_REPO: "endgame-secret:git_repo"

phases:
  install:
    commands:
    - sudo yum install docker -y
    - sudo yum install gettext -y
    - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.15/2023-01-11/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
    - aws sts get-caller-identity
    - cd frontend
    - echo "------ logging into the python ecr repo ------"
    - aws ecr get-login-password --region ${REGION} |sudo docker login --username AWS --password-stdin ${ACC_NO}.dkr.ecr.ap-south-1.amazonaws.com
    - echo "------ building the docker images ------"
    - sudo docker build -t frontend -f Dockerfile-modified .
    - sudo docker tag frontend ${FRONTEND_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
    - sudo docker tag frontend ${FRONTEND_REPO_URI}:latest
    - cd ../backend/
    - sudo docker build -t backend .
    - sudo docker tag backend ${BACKEND_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
    - sudo docker tag backend ${BACKEND_REPO_URI}:latest


    - echo "------ pushing docker images ------"
    - aws ecr get-login-password --region ${REGION} |sudo docker login --username AWS --password-stdin ${FRONTEND_REPO_URI}
    - sudo docker push ${FRONTEND_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
    - sudo docker push ${FRONTEND_REPO_URI}:latest


    - aws ecr get-login-password --region ${REGION} |sudo docker login --username AWS --password-stdin ${BACKEND_REPO_URI}
    - sudo docker push ${BACKEND_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
    - sudo docker push ${BACKEND_REPO_URI}:latest

  build:
    commands:

    - echo "------ getting the temporary creds ------"
    - CREDS=$(aws sts assume-role --role-arn ${ASSUME_ROLE_ARN} --role-session-name codebuild --duration-seconds 900)
    - export AWS_ACCESS_KEY_ID="$(echo ${CREDS} | jq -r '.Credentials.AccessKeyId')"
    - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDS} | jq -r '.Credentials.SecretAccessKey')"
    - export AWS_SESSION_TOKEN="$(echo ${CREDS} | jq -r '.Credentials.SessionToken')"
    - export AWS_EXPIRATION=$(echo ${CREDS} | jq -r '.Credentials.Expiration')

    - echo "------ logging into eks ------"
    - aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${REGION}

    - echo "------ changing the secret_tmp.yml file values ------"
    - cd ../
    - envsubst < secret_tmp.yml > manifests/secret.yml

    - echo "------ changing the backend-deploy_tmp.yml file values ------"
    - envsubst < backend-deploy_tmp.yml > manifests/backend-deploy.yml

    - echo "------ changing the frontend-deploy_tmp.yml file values ------"
    - envsubst < frontend-deploy_tmp.yml > manifests/frontend-deploy.yml


  post_build:
    commands:
    - echo "------ setting the github origin ------"
    - cd ..
    - pwd
    - ls
    # - echo "------ applying the manifest files ------"
    - git config --global user.name sumzz
    - git config --global user.email test@sumzz.online
    - git remote set-url origin https://${GIT_USER}:${GIT_PAT}@github.com/${GIT_USER}/${GIT_REPO}
    # check the PAT expiry time before running 
    - git add .
    - git commit -m "pipeline-commit-${CODEBUILD_BUILD_NUMBER}"
    - git push origin main
